/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 4.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// AddProfileToFolderRequest
    /// </summary>
    [DataContract(Name = "AddProfileToFolderRequest")]
    public partial class AddProfileToFolderRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddProfileToFolderRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddProfileToFolderRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddProfileToFolderRequest" /> class.
        /// </summary>
        /// <param name="profileId">Unique identifier of the profile. (required).</param>
        public AddProfileToFolderRequest(Guid profileId = default)
        {
            this.ProfileId = profileId;
        }

        /// <summary>
        /// Unique identifier of the profile.
        /// </summary>
        /// <value>Unique identifier of the profile.</value>
        /*
        <example>0036135c-6f62-429b-a9db-fd541aca96a7</example>
        */
        [DataMember(Name = "profileId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ProfileId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddProfileToFolderRequest {\n");
            sb.Append("  ProfileId: ").Append(ProfileId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
