/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// Defines the target location for profile export.
    /// </summary>
    [DataContract(Name = "ExportProfileRequest")]
    public partial class ExportProfileRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExportProfileRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExportProfileRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExportProfileRequest" /> class.
        /// </summary>
        /// <param name="path">Specifies the file path for exporting the profile. (required).</param>
        public ExportProfileRequest(string path = default(string))
        {
            // to ensure "path" is required (not null)
            if (path == null)
            {
                throw new ArgumentNullException("path is a required property for ExportProfileRequest and cannot be null");
            }
            this.Path = path;
        }

        /// <summary>
        /// Specifies the file path for exporting the profile.
        /// </summary>
        /// <value>Specifies the file path for exporting the profile.</value>
        /*
        <example>C:\Users\Windows 10\Kameleo Profiles\profile1.kameleo</example>
        */
        [DataMember(Name = "path", IsRequired = true, EmitDefaultValue = true)]
        public string Path { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExportProfileRequest {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Path (string) minLength
            if (this.Path != null && this.Path.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Path, length must be greater than 1.", new[] { "Path" });
            }

            yield break;
        }
    }

}
