/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// GeolocationChoice
    /// </summary>
    [DataContract(Name = "GeolocationChoice")]
    public partial class GeolocationChoice : IValidatableObject
    {

        /// <summary>
        /// Specifies how the geolocation will be spoofed. Possible values:  &#39;automatic&#39;: Automatically set the values based on the IP address  &#39;manual&#39;: Manually set the longitude and latitude in the profile  &#39;block&#39;: Completely block the Geolocation API  &#39;off&#39;: Turn off the spoofing, use the original settings
        /// </summary>
        /// <value>Specifies how the geolocation will be spoofed. Possible values:  &#39;automatic&#39;: Automatically set the values based on the IP address  &#39;manual&#39;: Manually set the longitude and latitude in the profile  &#39;block&#39;: Completely block the Geolocation API  &#39;off&#39;: Turn off the spoofing, use the original settings</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public GeolocationSpoofingType Value { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeolocationChoice" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GeolocationChoice() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeolocationChoice" /> class.
        /// </summary>
        /// <param name="value">Specifies how the geolocation will be spoofed. Possible values:  &#39;automatic&#39;: Automatically set the values based on the IP address  &#39;manual&#39;: Manually set the longitude and latitude in the profile  &#39;block&#39;: Completely block the Geolocation API  &#39;off&#39;: Turn off the spoofing, use the original settings (required).</param>
        /// <param name="extra">When the Geolocation spoofing is set to manual these extra settings will be used as well..</param>
        public GeolocationChoice(GeolocationSpoofingType value = default, GeolocationSpoofingOptions extra = default)
        {
            this.Value = value;
            this.Extra = extra;
        }

        /// <summary>
        /// When the Geolocation spoofing is set to manual these extra settings will be used as well.
        /// </summary>
        /// <value>When the Geolocation spoofing is set to manual these extra settings will be used as well.</value>
        [DataMember(Name = "extra", EmitDefaultValue = true)]
        public GeolocationSpoofingOptions Extra { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeolocationChoice {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Extra: ").Append(Extra).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
