/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 4.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// Defines whether the browser can save login credentials. Possible values are:  &#39;enabled&#39;: Credential saving is allowed.  &#39;disabled&#39;: Credential saving is blocked.
    /// </summary>
    /// <value>Defines whether the browser can save login credentials. Possible values are:  &#39;enabled&#39;: Credential saving is allowed.  &#39;disabled&#39;: Credential saving is blocked.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PasswordManagerType
    {
        /// <summary>
        /// Enum Enabled for value: enabled
        /// </summary>
        [EnumMember(Value = "enabled")]
        Enabled = 1,

        /// <summary>
        /// Enum Disabled for value: disabled
        /// </summary>
        [EnumMember(Value = "disabled")]
        Disabled = 2
    }

}
