/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 4.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// ProfileMinutesQuota
    /// </summary>
    [DataContract(Name = "ProfileMinutesQuota")]
    public partial class ProfileMinutesQuota : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileMinutesQuota" /> class.
        /// </summary>
        /// <param name="currentUsage">currentUsage.</param>
        /// <param name="maximumLimit">maximumLimit.</param>
        /// <param name="nextResetAt">nextResetAt.</param>
        public ProfileMinutesQuota(string currentUsage = default, string maximumLimit = default, DateTime nextResetAt = default)
        {
            this.CurrentUsage = currentUsage;
            this.MaximumLimit = maximumLimit;
            this.NextResetAt = nextResetAt;
        }

        /// <summary>
        /// Gets or Sets CurrentUsage
        /// </summary>
        [DataMember(Name = "currentUsage", EmitDefaultValue = false)]
        public string CurrentUsage { get; set; }

        /// <summary>
        /// Gets or Sets MaximumLimit
        /// </summary>
        [DataMember(Name = "maximumLimit", EmitDefaultValue = true)]
        public string MaximumLimit { get; set; }

        /// <summary>
        /// Gets or Sets NextResetAt
        /// </summary>
        [DataMember(Name = "nextResetAt", EmitDefaultValue = false)]
        public DateTime NextResetAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProfileMinutesQuota {\n");
            sb.Append("  CurrentUsage: ").Append(CurrentUsage).Append("\n");
            sb.Append("  MaximumLimit: ").Append(MaximumLimit).Append("\n");
            sb.Append("  NextResetAt: ").Append(NextResetAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
