/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 4.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// ProxyChoice
    /// </summary>
    [DataContract(Name = "ProxyChoice")]
    public partial class ProxyChoice : IValidatableObject
    {

        /// <summary>
        /// Proxy connection settings of the profiles. Possible values:  &#39;none&#39;: Direct connection without any proxy.  &#39;http&#39;: Use a HTTP proxy for upstream communication.  &#39;socks5&#39;: Use a SOCKS5 proxy for upstream communication.  &#39;ssh&#39;: Use an SSH connection for upstream communication. Basically a SOCKS5 proxy created at the given SSH host.
        /// </summary>
        /// <value>Proxy connection settings of the profiles. Possible values:  &#39;none&#39;: Direct connection without any proxy.  &#39;http&#39;: Use a HTTP proxy for upstream communication.  &#39;socks5&#39;: Use a SOCKS5 proxy for upstream communication.  &#39;ssh&#39;: Use an SSH connection for upstream communication. Basically a SOCKS5 proxy created at the given SSH host.</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public ProxyConnectionType Value { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProxyChoice" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProxyChoice() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProxyChoice" /> class.
        /// </summary>
        /// <param name="value">Proxy connection settings of the profiles. Possible values:  &#39;none&#39;: Direct connection without any proxy.  &#39;http&#39;: Use a HTTP proxy for upstream communication.  &#39;socks5&#39;: Use a SOCKS5 proxy for upstream communication.  &#39;ssh&#39;: Use an SSH connection for upstream communication. Basically a SOCKS5 proxy created at the given SSH host. (required).</param>
        /// <param name="extra">Represents a server connection. It can be used as a proxy server connection as well..</param>
        public ProxyChoice(ProxyConnectionType value = default, Server extra = default)
        {
            this.Value = value;
            this.Extra = extra;
        }

        /// <summary>
        /// Represents a server connection. It can be used as a proxy server connection as well.
        /// </summary>
        /// <value>Represents a server connection. It can be used as a proxy server connection as well.</value>
        [DataMember(Name = "extra", EmitDefaultValue = true)]
        public Server Extra { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProxyChoice {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Extra: ").Append(Extra).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
