/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 4.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// Proxy connection settings of the profiles. Possible values:  &#39;none&#39;: Direct connection without any proxy.  &#39;http&#39;: Use a HTTP proxy for upstream communication.  &#39;socks5&#39;: Use a SOCKS5 proxy for upstream communication.  &#39;ssh&#39;: Use an SSH connection for upstream communication. Basically a SOCKS5 proxy created at the given SSH host.
    /// </summary>
    /// <value>Proxy connection settings of the profiles. Possible values:  &#39;none&#39;: Direct connection without any proxy.  &#39;http&#39;: Use a HTTP proxy for upstream communication.  &#39;socks5&#39;: Use a SOCKS5 proxy for upstream communication.  &#39;ssh&#39;: Use an SSH connection for upstream communication. Basically a SOCKS5 proxy created at the given SSH host.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ProxyConnectionType
    {
        /// <summary>
        /// Enum None for value: none
        /// </summary>
        [EnumMember(Value = "none")]
        None = 1,

        /// <summary>
        /// Enum Http for value: http
        /// </summary>
        [EnumMember(Value = "http")]
        Http = 2,

        /// <summary>
        /// Enum Socks5 for value: socks5
        /// </summary>
        [EnumMember(Value = "socks5")]
        Socks5 = 3,

        /// <summary>
        /// Enum Ssh for value: ssh
        /// </summary>
        [EnumMember(Value = "ssh")]
        Ssh = 4
    }

}
