/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 4.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// QuotaStatistics
    /// </summary>
    [DataContract(Name = "QuotaStatistics")]
    public partial class QuotaStatistics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuotaStatistics" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public QuotaStatistics()
        {
        }

        /// <summary>
        /// Indicates the current usage, always a non-negative value.
        /// </summary>
        /// <value>Indicates the current usage, always a non-negative value.</value>
        [DataMember(Name = "currentUsage", IsRequired = true, EmitDefaultValue = true)]
        public int CurrentUsage { get; private set; }

        /// <summary>
        /// Returns false as CurrentUsage should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCurrentUsage()
        {
            return false;
        }
        /// <summary>
        /// Indicates the maximum permitted value, with -1 implying no limit.
        /// </summary>
        /// <value>Indicates the maximum permitted value, with -1 implying no limit.</value>
        [DataMember(Name = "maximumLimit", IsRequired = true, EmitDefaultValue = true)]
        public int MaximumLimit { get; private set; }

        /// <summary>
        /// Returns false as MaximumLimit should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMaximumLimit()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QuotaStatistics {\n");
            sb.Append("  CurrentUsage: ").Append(CurrentUsage).Append("\n");
            sb.Append("  MaximumLimit: ").Append(MaximumLimit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
