/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// RunningProfilesStatistics
    /// </summary>
    [DataContract(Name = "RunningProfilesStatistics")]
    public partial class RunningProfilesStatistics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunningProfilesStatistics" /> class.
        /// </summary>
        /// <param name="automated">automated.</param>
        /// <param name="manual">manual.</param>
        public RunningProfilesStatistics(QuotaStatistics automated = default(QuotaStatistics), QuotaStatistics manual = default(QuotaStatistics))
        {
            this.Automated = automated;
            this.Manual = manual;
        }

        /// <summary>
        /// Gets or Sets Automated
        /// </summary>
        [DataMember(Name = "automated", EmitDefaultValue = false)]
        public QuotaStatistics Automated { get; set; }

        /// <summary>
        /// Gets or Sets Manual
        /// </summary>
        [DataMember(Name = "manual", EmitDefaultValue = false)]
        public QuotaStatistics Manual { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunningProfilesStatistics {\n");
            sb.Append("  Automated: ").Append(Automated).Append("\n");
            sb.Append("  Manual: ").Append(Manual).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
