/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 4.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// ShareAccessRequest
    /// </summary>
    [DataContract(Name = "ShareAccessRequest")]
    public partial class ShareAccessRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShareAccessRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShareAccessRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShareAccessRequest" /> class.
        /// </summary>
        /// <param name="roleId">Id of the selected role. (required).</param>
        /// <param name="userId">Id of the selected user. (required).</param>
        public ShareAccessRequest(Guid roleId = default, Guid userId = default)
        {
            this.RoleId = roleId;
            this.UserId = userId;
        }

        /// <summary>
        /// Id of the selected role.
        /// </summary>
        /// <value>Id of the selected role.</value>
        [DataMember(Name = "roleId", IsRequired = true, EmitDefaultValue = true)]
        public Guid RoleId { get; set; }

        /// <summary>
        /// Id of the selected user.
        /// </summary>
        /// <value>Id of the selected user.</value>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public Guid UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShareAccessRequest {\n");
            sb.Append("  RoleId: ").Append(RoleId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
