/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// WebglMeta
    /// </summary>
    [DataContract(Name = "WebglMeta")]
    public partial class WebglMeta : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebglMeta" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WebglMeta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebglMeta" /> class.
        /// </summary>
        /// <param name="vendor">The UnmaskedVendor field from WebGL context (required).</param>
        /// <param name="renderer">The UnmaskedRenderer field from WebGL context.</param>
        public WebglMeta(string vendor = default(string), string renderer = default(string))
        {
            // to ensure "vendor" is required (not null)
            if (vendor == null)
            {
                throw new ArgumentNullException("vendor is a required property for WebglMeta and cannot be null");
            }
            this.Vendor = vendor;
            this.Renderer = renderer;
        }

        /// <summary>
        /// The UnmaskedVendor field from WebGL context
        /// </summary>
        /// <value>The UnmaskedVendor field from WebGL context</value>
        /*
        <example>Google Inc. (AMD)</example>
        */
        [DataMember(Name = "vendor", IsRequired = true, EmitDefaultValue = true)]
        public string Vendor { get; set; }

        /// <summary>
        /// The UnmaskedRenderer field from WebGL context
        /// </summary>
        /// <value>The UnmaskedRenderer field from WebGL context</value>
        /*
        <example>ANGLE (AMD, AMD Radeon(TM) RX Vega 11 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)</example>
        */
        [DataMember(Name = "renderer", EmitDefaultValue = true)]
        public string Renderer { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebglMeta {\n");
            sb.Append("  Vendor: ").Append(Vendor).Append("\n");
            sb.Append("  Renderer: ").Append(Renderer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
