/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// Specifies how the WebRTC will be spoofed. Possible values:  &#39;automatic&#39;: Automatically set the webRTC public IP by the IP  &#39;manual&#39;: Manually override the webRTC public IP and private IP in the profile  &#39;block&#39;: Block the WebRTC functionality  &#39;off&#39;: Turn off the spoofing, use the original settings
    /// </summary>
    /// <value>Specifies how the WebRTC will be spoofed. Possible values:  &#39;automatic&#39;: Automatically set the webRTC public IP by the IP  &#39;manual&#39;: Manually override the webRTC public IP and private IP in the profile  &#39;block&#39;: Block the WebRTC functionality  &#39;off&#39;: Turn off the spoofing, use the original settings</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WebRtcSpoofingType
    {
        /// <summary>
        /// Enum Automatic for value: automatic
        /// </summary>
        [EnumMember(Value = "automatic")]
        Automatic = 1,

        /// <summary>
        /// Enum Manual for value: manual
        /// </summary>
        [EnumMember(Value = "manual")]
        Manual = 2,

        /// <summary>
        /// Enum Block for value: block
        /// </summary>
        [EnumMember(Value = "block")]
        Block = 3,

        /// <summary>
        /// Enum Off for value: off
        /// </summary>
        [EnumMember(Value = "off")]
        Off = 4
    }

}
