// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kameleo.LocalApiClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice
        /// class.
        /// </summary>
        public GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice
        /// class.
        /// </summary>
        /// <param name="value">Possible values include: 'automatic', 'manual',
        /// 'block', 'off'</param>
        public GeolocationSpoofingTypeGeolocationSpoofingOptionsMultiLevelChoice(string value, GeolocationSpoofingOptions extra = default(GeolocationSpoofingOptions))
        {
            Value = value;
            Extra = extra;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'automatic', 'manual',
        /// 'block', 'off'
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extra")]
        public GeolocationSpoofingOptions Extra { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Value == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Value");
            }
            if (Extra != null)
            {
                Extra.Validate();
            }
        }
    }
}
