// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kameleo.LocalApiClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProblemResponse
    {
        /// <summary>
        /// Initializes a new instance of the ProblemResponse class.
        /// </summary>
        public ProblemResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProblemResponse class.
        /// </summary>
        public ProblemResponse(int? code = default(int?), IDictionary<string, IList<string>> error = default(IDictionary<string, IList<string>>))
        {
            Code = code;
            Error = error;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public int? Code { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public IDictionary<string, IList<string>> Error { get; set; }

    }
}
