// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kameleo.LocalApiClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a server connection. It can be used as a proxy server
    /// connection as well.
    /// </summary>
    public partial class Server
    {
        /// <summary>
        /// Initializes a new instance of the Server class.
        /// </summary>
        public Server()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Server class.
        /// </summary>
        /// <param name="host">Gets or sets the hostname where the service is
        /// provided from.</param>
        /// <param name="port">Gets or sets the port where the service is
        /// provided from.</param>
        /// <param name="id">Gets or sets the identity information provided for
        /// the service. This could be a custom id or username or anything
        /// which identifies a resource on the remote service. Use it as a
        /// proxy username. This field is optional.</param>
        /// <param name="secret">Gets or sets the shared secret between the
        /// client and the service provider. Use it as a proxy password. This
        /// field is optional.</param>
        public Server(string host, int port, string id = default(string), string secret = default(string))
        {
            Host = host;
            Port = port;
            Id = id;
            Secret = secret;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the hostname where the service is provided from.
        /// </summary>
        [JsonProperty(PropertyName = "host")]
        public string Host { get; set; }

        /// <summary>
        /// Gets or sets the port where the service is provided from.
        /// </summary>
        [JsonProperty(PropertyName = "port")]
        public int Port { get; set; }

        /// <summary>
        /// Gets or sets the identity information provided for the service.
        /// This could be a custom id or username or anything which identifies
        /// a resource on the remote service. Use it as a proxy username. This
        /// field is optional.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the shared secret between the client and the service
        /// provider. Use it as a proxy password. This field is optional.
        /// </summary>
        [JsonProperty(PropertyName = "secret")]
        public string Secret { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Host == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Host");
            }
        }
    }
}
