// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kameleo.LocalApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ShareAccessRequest
    {
        /// <summary>
        /// Initializes a new instance of the ShareAccessRequest class.
        /// </summary>
        public ShareAccessRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ShareAccessRequest class.
        /// </summary>
        /// <param name="roleId">Id of the selected role.</param>
        /// <param name="userId">Id of the selected user.</param>
        public ShareAccessRequest(System.Guid roleId, System.Guid userId)
        {
            RoleId = roleId;
            UserId = userId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets id of the selected role.
        /// </summary>
        [JsonProperty(PropertyName = "roleId")]
        public System.Guid RoleId { get; set; }

        /// <summary>
        /// Gets or sets id of the selected user.
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public System.Guid UserId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
