// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kameleo.LocalApiClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SharingOptionsResponse
    {
        /// <summary>
        /// Initializes a new instance of the SharingOptionsResponse class.
        /// </summary>
        public SharingOptionsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SharingOptionsResponse class.
        /// </summary>
        /// <param name="users">List of users in your team.</param>
        /// <param name="roles">List of roles you can give the users.</param>
        public SharingOptionsResponse(IList<User> users = default(IList<User>), IList<GroupRole> roles = default(IList<GroupRole>))
        {
            Users = users;
            Roles = roles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of users in your team.
        /// </summary>
        [JsonProperty(PropertyName = "users")]
        public IList<User> Users { get; set; }

        /// <summary>
        /// Gets or sets list of roles you can give the users.
        /// </summary>
        [JsonProperty(PropertyName = "roles")]
        public IList<GroupRole> Roles { get; set; }

    }
}
