// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kameleo.LocalApiClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TestProxyResponse
    {
        /// <summary>
        /// Initializes a new instance of the TestProxyResponse class.
        /// </summary>
        public TestProxyResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TestProxyResponse class.
        /// </summary>
        /// <param name="isValidProxy">Tells weather the proxy is valid or
        /// not.</param>
        /// <param name="message">A written message about the result of the
        /// test.</param>
        public TestProxyResponse(bool isValidProxy, string message)
        {
            IsValidProxy = isValidProxy;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets tells weather the proxy is valid or not.
        /// </summary>
        [JsonProperty(PropertyName = "isValidProxy")]
        public bool IsValidProxy { get; set; }

        /// <summary>
        /// Gets or sets a written message about the result of the test.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Message == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Message");
            }
        }
    }
}
