// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kameleo.LocalApiClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TestProxyRequest
    {
        /// <summary>
        /// Initializes a new instance of the TestProxyRequest class.
        /// </summary>
        public TestProxyRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TestProxyRequest class.
        /// </summary>
        public TestProxyRequest(ProxyConnectionTypeServerMultiLevelChoice proxy)
        {
            Proxy = proxy;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "proxy")]
        public ProxyConnectionTypeServerMultiLevelChoice Proxy { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Proxy == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Proxy");
            }
            if (Proxy != null)
            {
                Proxy.Validate();
            }
        }
    }
}
